services:
  exambyteDB:
    image: postgres:15-alpine
    container_name: exambyte_postgres

    ports:
      - "127.0.0.1:5432:5432"

    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"

    volumes:
      - exambyte_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: exambyte_app

    environment:
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}

    depends_on:
      - exambyteDB

  caddy:
    image: caddy:2
    container_name: exambyte_caddy

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

    depends_on:
      - app

volumes:
  exambyte_data:
  caddy_data:
  caddy_config: