@startuml
actor Administrator
actor Student
actor Korrektor

usecase Testfragen
component ExamByte
usecase Bewertung
usecase Ergebnis
usecase Gesamtübersicht
usecase Antworten

Administrator --> Testfragen : erstellt
Student --> Antworten : erstellt
ExamByte --> Antworten : bewertet MC-Antworten
Korrektor --> Antworten : bewertet
Korrektor --> Bewertung : erstellt
ExamByte --> Bewertung : erstellt
ExamByte --> Ergebnis : veröffentlicht
Student --> Ergebnis : kann einsehen
Testfragen --> ExamByte : gespeichert in
ExamByte --> Gesamtübersicht : erstellt
Gesamtübersicht --> Administrator : wird angezeigt
@enduml
