@startuml
actor Administrator
actor Student
actor Reviewer
database PostgreSQL

cloud {
    ["GitHub OAuth2"]
}

component "ExamByte"

Administrator --> "ExamByte" : Create exams, view overview
Student --> "ExamByte" : Take exams
Reviewer --> "ExamByte" : Grade exams
"ExamByte" --> PostgreSQL : Store / retrieve data

Student --> ["GitHub OAuth2"] : Authentication
Reviewer --> ["GitHub OAuth2"] : Authentication
Administrator --> ["GitHub OAuth2"] : Authentication
@enduml