@startuml
actor Administrator
actor Student
actor Korrektor
database PostgreSQL

cloud {
    ["Github OAuth2"]
}

component "ExamByte"


Administrator --> "ExamByte" : Test erstellen, Übersicht einsehen
Student --> "ExamByte" : Tests bearbeiten
Korrektor --> "ExamByte" : Tests bewerten
"ExamByte" --> PostgreSQL : Daten speichern / abrufen
Student --> ["Github OAuth2"] : Anmeldung
Korrektor --> ["Github OAuth2"] : Anmeldung
Administrator --> ["Github OAuth2"] : Anmeldung
@enduml
